# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b2802843eb189c44b7dabdf4babd1820"
application_url = "https://xpaw-admin.onrender.com"
embedded = true
name = "XPaw Admin"

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_customers,read_fulfillments,read_inventory,read_locales,read_locations,read_orders,read_products,read_publications,read_translations,write_customers,write_files,write_fulfillments,write_inventory,write_metaobject_definitions,write_metaobjects,write_orders,write_products,write_publications,write_translations"

[auth]
redirect_urls = [ "https://xpaw-admin.onrender.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
