# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fe507970e7417967c9ba4adfcb2be1b8"
name = "Chatgpt Tutorial"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_metaobjects,write_metaobject_definitions,read_locations,write_inventory"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
