# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "46f51e8779f65ac2025ac15a48e5ca65"
name = "Chatgpt Tutorial"
application_url = "https://localhost:3458"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locations,read_products,write_inventory,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://localhost:3458/auth/callback" ]
