// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/app/collections/:id": {
    params: {
      "id": string;
    };
  };
  "/app/products/:id": {
    params: {
      "id": string;
    };
  };
  "/app/tags/:tag": {
    params: {
      "tag": string;
    };
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/collections": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/products": {
    params: {};
  };
  "/app/upload": {
    params: {};
  };
  "/app/tags": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/app/collections/:id" | "/app/products/:id" | "/app/tags/:tag" | "/auth/login" | "/auth/*" | "/app" | "/app/collections" | "/app/additional" | "/app/products" | "/app/upload" | "/app/tags";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/app_.collections.$id.jsx": {
    id: "routes/app_.collections.$id";
    page: "/app/collections/:id";
  };
  "routes/app_.products.$id.jsx": {
    id: "routes/app_.products.$id";
    page: "/app/products/:id";
  };
  "routes/app_.tags.$tag.jsx": {
    id: "routes/app_.tags.$tag";
    page: "/app/tags/:tag";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/collections" | "/app/additional" | "/app/products" | "/app/upload" | "/app/tags";
  };
  "routes/app.collections.jsx": {
    id: "routes/app.collections";
    page: "/app/collections";
  };
  "routes/app.additional.jsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.products.jsx": {
    id: "routes/app.products";
    page: "/app/products";
  };
  "routes/app.upload.jsx": {
    id: "routes/app.upload";
    page: "/app/upload";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.tags.jsx": {
    id: "routes/app.tags";
    page: "/app/tags";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/app_.collections.$id": typeof import("./app/routes/app_.collections.$id.jsx");
  "routes/app_.products.$id": typeof import("./app/routes/app_.products.$id.jsx");
  "routes/app_.tags.$tag": typeof import("./app/routes/app_.tags.$tag.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.collections": typeof import("./app/routes/app.collections.jsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.jsx");
  "routes/app.products": typeof import("./app/routes/app.products.jsx");
  "routes/app.upload": typeof import("./app/routes/app.upload.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
  "routes/app.tags": typeof import("./app/routes/app.tags.jsx");
};